### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang-idea#105]
I'm getting this error with JBang IDEA plugin 0.24.5:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.jbang.idea.actions.SyncDependenciesAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.jbang.intellij.JBangPlugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

IDEA info:

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Red Hat Inc / George Gastaldi
Subscription is active until June 7, 2024.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  manjaro.mpb (1.9)
  org.intellij.plugins.hcl (241.14494.150)
  name.kropp.intellij.makefile (241.14494.150)
  net.ashald.envfile (3.4.2)
  com.redhat.devtools.intellij.telemetry (1.1.0.52)
  com.redhat.devtools.lsp4ij (0.0.1-20240117-153055)
  CheckStyle-IDEA (5.89.1)
  PlantUML integration (7.8.1-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.41.13)
  com.redhat.devtools.intellij.quarkus (1.30.1-20240111-012605)
  MavenRunHelper (4.28.0-IJ2022.2)
  dev.jbang.intellij.JBangPlugin (0.24.5)
  com.dmarcotte.handlebars (241.14494.150)
  mobi.hsz.idea.gitignore (4.5.2)
Kotlin: 241.14494.240-IJ
```

**Comment by linux-china** [comment]
Fixed with 0.24.6
