### ISSUE TITLE
toolbar creation exception: Please call toolbar.setTargetComponent() explicitly.

### ISSUE THREAD

**Issue by koppor** [jbangdev/jbang-idea#110]
```yaml
IntelliJ IDEA 2024.2.0.2 (Ultimate Edition)
Build #IU-242.20224.419, built on August 19, 2024
Licensed to JabRef / Oliver Kopp
Subscription is active until November 14, 2024.
For non-commercial open source development only.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3100M
Cores: 16
Registry:
  ide.experimental.ui=true
  ide.ui.new.file.chooser=true
  i18n.locale=
Non-Bundled Plugins:
  palantir-java-format (2.50.0)
  CheckStyle-IDEA (5.92.0)
  dev.jbang.intellij.JBangPlugin (0.24.6)
  com.github.copilot (1.5.20.6554)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  com.github.kawamataryo.copygithublink (0.5.3)
Kotlin: 242.20224.419-IJ
```

```
2024-08-22 20:59:41,665 [  60330]   WARN - #c.i.o.a.i.ActionToolbarImpl - 'ACTION_TOOLBAR' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly.
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:131)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.createActionToolbarImpl(ActionManagerImpl.kt:1612)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$createActionToolbarImpl(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.kt:326)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.kt:310)
	at dev.jbang.idea.ui.JBangToolWindowPanel.createToolbar(JBangToolWindowFactory.kt:45)
	at dev.jbang.idea.ui.JBangToolWindowPanel.<init>(JBangToolWindowFactory.kt:37)
	at dev.jbang.idea.ui.JBangToolWindowFactory.createToolWindowContent(JBangToolWindowFactory.kt:23)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:667)No
```

**Comment by maxandersen** [comment]
I dont see this error/warning in recent builds. assuming not an issue anymore but if you still do please reopen/create new.
